### ISSUE TITLE
Propuesta de diseños de pantallas

### ISSUE THREAD

**Issue by AmadeusLiz** [AmadeusLiz/toDo#1]
Mandar el diseño que se espera tenga la App

**Comment by rixitrox** [comment]
![desgin](https://user-images.githubusercontent.com/73371604/101366325-71b04b80-386a-11eb-9abe-88ecb37d2652.png)
el estilo Gradient 2.0 creo que entraria bien para una app de "to do list" se senteria algo nuevo/futuristo el estilo,
tener el un tab donde saldria "daily task"  por ejemplo , para el usuario vea lo que tiene que hacer dia a dia, tener otra tab para poner lista en un dia espefico, y un tercero con el tab de poner un task con hora , tipo alarma

**Comment by AmadeusLiz** [comment]
Hora y tipo de alarma... si ñudieras buscar como se hace eso estaria excelente. Asi sabriamos si en verdad podriamos incorporarlo, recorda que esto es para el martes

**Comment by rixitrox** [comment]
Vale ahorita voy como se implementa

**Comment by AmadeusLiz** [comment]
![Screenshot_20201208-104152_Todoist](https://user-images.githubusercontent.com/71053273/101546788-ee2c5280-396e-11eb-8f48-24fa7d63dc5f.jpg)
Mira que pense en algo asi para que salgan las tareas por havrr en la pantalla principal
Al lado un circulito que al tocarlo indica que ya realicé ka tarea y se coloca una flechita.. eso podriamos hacerlo con iconos!

**Comment by AmadeusLiz** [comment]
![Whiteboard 2 -01](https://user-images.githubusercontent.com/71053273/101564224-5d666e80-3990-11eb-8c8b-206ab5780134.png)
Bueno como ya decidimos en zoom, estos serian los diseños de nuestras pantallas!

**Comment by AmadeusLiz** [comment]
Perdon, lo cerre accidental..
Usaremos lo del estilo gradient que mencionaste! Por aqui manda como luce con los colores que escogimos para ver de paso qe color de texto deberia tener

**Comment by rixitrox** [comment]
![2](https://user-images.githubusercontent.com/73371604/101793679-ae2eb200-3acb-11eb-9dc3-926cc6f12e38.png)
![3](https://user-images.githubusercontent.com/73371604/101793700-b4249300-3acb-11eb-87aa-4d7af29578ed.png)
![4](https://user-images.githubusercontent.com/73371604/101793747-bdadfb00-3acb-11eb-8001-4f02bfe70416.png)
![5](https://user-images.githubusercontent.com/73371604/101793772-c69ecc80-3acb-11eb-99b2-962fbfed63c0.png)
![6](https://user-images.githubusercontent.com/73371604/101793806-cef70780-3acb-11eb-9d66-3549ed7d970a.png)
![7](https://user-images.githubusercontent.com/73371604/101793836-d61e1580-3acb-11eb-9978-a33c48971472.png)
![1](https://user-images.githubusercontent.com/73371604/101793857-dc13f680-3acb-11eb-9cf9-6d59f627a8a3.png)

**Comment by AmadeusLiz** [comment]
![imagen](https://user-images.githubusercontent.com/71053273/101833958-4e51fe80-3aff-11eb-9eb0-800b20aa494b.png)
Me gusta esta, que opinas?
Igual creo que la letra blanca queda mejor

**Comment by rixitrox** [comment]
Esta bien, quedemos con el banco

**Comment by rixitrox** [comment]
para crear los grandients, vi que con react native no se necesita adicionar muchas cosas, solo un install de "yarn add react-native-linear-gradient" y para IOS un adcional "npx pod-install" para que funcione bien en ambas plataformas.
Una buena guia para utilizar el gradiente lineal fue : https://blog.logrocket.com/understanding-react-native-linear-gradient/
en los ejemplos usan nombres de colores pero tambien se puede usar el codigo hexadecimal, cual nosotros ya al menos sabemos cuales usar gracias a la paleta de colores que eligimos

**Comment by AmadeusLiz** [comment]
Oooh okay okay, bueno el codigo ya está empezado al menos lo básico
Tenes que ir impolementando eso, yo vere lo de la grafica de progreso

podes ver este video de [como usar github](https://www.youtube.com/watch?v=kEPF-MWGq1w), es un tutorial que te puede servir

Tenes que crear tu rama para que vayas trabajando ahi, si te fijas actualmente hay dos, en la mia esta lo que ocupas para iniciar, todas tus cosas las subes a tu rama..

![imagen](https://user-images.githubusercontent.com/71053273/101951046-f0cfb780-3bbb-11eb-871b-7b74bc2abef2.png)

**Comment by rixitrox** [comment]
Ya puede mi propia rama , y ya con expo estoy experimentando

**Comment by AmadeusLiz** [comment]
Mmm "experimentando" a menos de 24hrs de la entrega del proyecto.. no suena bien
