### ISSUE TITLE
Logo de la App

### ISSUE THREAD

**Issue by AmadeusLiz** [AmadeusLiz/toDo#2]
Mandar propuestas para logos

**Comment by AmadeusLiz** [comment]
![Copia de LYRICAL(9)](https://user-images.githubusercontent.com/71053273/101532541-53297d80-395a-11eb-93c0-4ad6efe91303.png)
![Copia de LYRICAL(8)](https://user-images.githubusercontent.com/71053273/101532543-545aaa80-395a-11eb-82b7-ec8b59f7ea5c.png)
![Copia de LYRICAL(7)](https://user-images.githubusercontent.com/71053273/101532552-56bd0480-395a-11eb-9a15-602bea0676eb.png)

**Comment by rixitrox** [comment]
![](https://user-images.githubusercontent.com/71053273/101532552-56bd0480-395a-11eb-9a15-602bea0676eb.png)
este me parace bien

**Comment by AmadeusLiz** [comment]
Listo, ese queda entonces
