### ISSUE TITLE
Nombre de la App

### ISSUE THREAD

**Issue by AmadeusLiz** [AmadeusLiz/toDo#3]
Propuesta de nombre de la App

**Comment by AmadeusLiz** [comment]
Pues originalmente pense en ponerle ToDo a la App, un nombre concreto xD, y talvez asi de logo eso de nike de "just do it!"
No se si te parece bien o tenes otra propuesta mejor @rixitrox

**Comment by rixitrox** [comment]
Xdxd se podría, también pensé en "Ultimate list". Con "The ultimate to do
list"

**Comment by AmadeusLiz** [comment]
Okay, consultare a la gente cual les gusta mas haha

**Comment by AmadeusLiz** [comment]
Pues a la mayoria de los q consulté les gustó más ToDo
Entonces no se cómo quedamos, escogemos entre las dos propuestas al azar? o dejamos ese de ToDo

**Comment by rixitrox** [comment]
si le gusto mas ToDo, pues me parace bien
