### ISSUE TITLE
Estructura de la base de datos

### ISSUE THREAD

**Issue by AmadeusLiz** [AmadeusLiz/toDo#4]
Determinar la estructura que tendra la base de datos

**Comment by AmadeusLiz** [comment]
Tenia pensado dejar una estructura un poco sencilla para no complicarnos mucho
Una tabla nada mas que contenga:

- id

- todo (la tarea por hacer)

- status (este lo tengo pensado utilizar para mostrar graficos de las tareas hechas y por hacer, asi como de 10 tareas he completado 5 por ejemplo..)

**Comment by rixitrox** [comment]
me parace bien, para no complicarnos, los de graficos , me para rico xd, se podria dejar en la pantalla principal o en otros tab, como "progress" .
