### ISSUE TITLE
Paleta de colores

### ISSUE THREAD

**Issue by AmadeusLiz** [AmadeusLiz/toDo#5]
Propuestas

**Comment by AmadeusLiz** [comment]
![imagen](https://user-images.githubusercontent.com/71053273/101387601-433f6a00-3884-11eb-8611-797e324d53d6.png)
Esta paleta me gustó bastante, asi que me gustaria usarla nuevamente, si te parece

**Comment by rixitrox** [comment]
#f2c947
#abd7eb
#2c9a8e
#01463f
#47485d
![image](https://user-images.githubusercontent.com/73371604/101527696-f7f48c80-3953-11eb-87e8-2f2d0c07bc5c.png)

**Comment by AmadeusLiz** [comment]
Me gusta la que enviaste
Podriamos usar como color Primario el penultimo color #01463f
y secundario el amarillo #f2c947
